version: "3"
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        grafanaversion: 5.0.0-11790beta1
    environment:
      - GF_SECURITY_ADMIN_USER=grafanaAdmin
      - GF_SECURITY_ADMIN_PASSWORD=monitoringLove
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=grafanadb
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSSWORD=gra7anaDbSecr3t
      # - GF_LOG_LEVEL=debug
    command: ["/scripts/wait-for-postgres.sh", "postgres", "--", "/grafana/bin/grafana-server", "web"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - graphite
    networks:
      - default
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    networks:
      - default
  graphite:
    image: graphiteapp/docker-graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  graphite-writer:
    build:
      context: .
      dockerfile: Dockerfile-graphite-writer
    command: ["/graphite-writer/write-sin-to-graphite.sh"]
    networks: 
      - default
    depends_on:
      - graphite
networks:
  default:
