version: "3"
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        grafanaversion: 5.0.0-10969pre1
    command: ["/scripts/wait-for-postgres.sh", "postgres", "--", "/grafana/bin/grafana-server", "web"]
    ports:
      - "3000:3000"
    links:
      - postgres
      - graphite
    networks:
      - monitoringlove
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    networks:
      - monitoringlove
  graphite:
    image: graphiteapp/docker-graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
networks:
  monitoringlove:
