#!/bin/bash
set -e

echo "*** Creating GRAFANA database..."
# $(create_database ${GRAFANA_DB_NAME} ${GRAFANA_DB_USER} ${GRAFANA_DB_PASSWORD})
grafana_create_heredoc=<<-EOSQL
    CREATE USER $GRAFANA_DB_USER WITH PASSWORD '$GRAFANA_DB_PASSWORD';
    CREATE DATABASE $GRAFANA_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE "$GRAFANA_DB_NAME" TO $GRAFANA_DB_USER;
EOSQL

echo $grafana_create_heredoc
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" 

# echo "*** Creating ZABBIX database..."
# # $(create_database ${ZABBIX_DB_NAME} ${ZABBIX_DB_USER} ${ZABBIX_DB_PASSWORD})
# psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
#     CREATE USER ${ZABBIX_DB_USER} WITH PASSWORD '${ZABBIX_DB_PASSWORD}';
#     CREATE DATABASE ${ZABBIX_DB_NAME};
#     GRANT ALL PRIVILEGES ON DATABASE "${ZABBIX_DB_NAME}" TO ${ZABBIX_DB_USER};
# EOSQL

# echo "*** Creating ZABBIXWEB database..."
# # $(create_database ${ZABBIXWEB_DB_NAME} ${ZABBIXWEB_DB_USER} ${ZABBIXWEB_DB_PASSWORD})
# psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
#     CREATE USER ${ZABBIXWEB_DB_USER} WITH PASSWORD '${ZABBIXWEB_DB_PASSWORD}';
#     CREATE DATABASE ${ZABBIXWEB_DB_NAME};
#     GRANT ALL PRIVILEGES ON DATABASE "${ZABBIXWEB_DB_NAME}" TO ${ZABBIXWEB_DB_USER};
# EOSQL